#!/bin/sh

copy() {
  [ -s "$2" -o -f "$2" ] && return 1
  cp -pR "$1" "$2" && echo "\`$1' -> \`$2'" || exit 1
}

for src in "$@"; do
  [ `basename "$src"` = . -o `basename "$src"` = .. ] && src=`cd "$src" && pwd`
  dst="$src.`date +%Y%m%d`"
  copy "$src" "$dst" && continue
  i=0
  while :; do
    copy "$src" "$dst.$i" && break
    i=`expr $i + 1`
  done
done
