#!/bin/sh

copy() {
  [ -e "$2" ] && return 1
  cp -piR "$1" "$2" && ls -ld "$1" "$2"
  return 0
}

for src in "$@"; do
  [ `basename "$src"` = . -o `basename "$src"` = .. ] && src=`cd "$src" && pwd`
  dst="$src.`date +%Y%m%d`"
  copy "$src" "$dst" && continue
  dst="$dst.`date +%H%M%S`"
  copy "$src" "$dst" && continue
  i=0
  while :; do
    copy "$src" "$dst.$i" && break
    i=`expr $i + 1`
  done
done
